import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Use a valid font like 'Inter' from Google Fonts
import "./globals.css";
import Slieder from "./component/layout/Slie/page";
import Navpage from "./component/navpage/page";

// Example of valid Google Font import
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <div className="flex flex-row h-auto">
          {/* Sidebar */}
          <div className="relative shrink-0 bg-white z-[1]">
            <Slieder />
          </div>

          {/* Main Content */}
          <main className="absolute bg-black min-h-[17.75rem] w-full">
            <nav
              style={{ marginLeft: "17.5rem" }}
              className="flex items-center justify-between p-4 ml-[17.5rem] sm:ml-0"
            >
              <div className="flex-col text-xl font-bold text-white mx-3">
                <Navpage />
              </div>

              <div className="ml-4 flex space-x-4 items-center">
                <img
                  src="/nav/loupe.png"
                  alt="Image 1"
                  className="w-[1.2rem] h-[1.2rem] filter grayscale invert"
                />
                <img
                  src="/nav/user.png"
                  alt="Image 1"
                  className="w-[1.2rem] h-[1.2rem] filter grayscale invert"
                />
                <span className="text-white text-[1.2rem]">Sign in</span>
                <img
                  src="/nav/setting.png"
                  alt="Image 1"
                  className="w-[1.2rem] h-[1.2rem] filter grayscale invert"
                />
                <img
                  src="/nav/bellD.png"
                  alt="Image 1"
                  className="w-[1.2rem] h-[1.2rem] filter grayscale invert"
                />
              </div>
            </nav>
          </main>

          {/* Content Area */}
          <div
            className="relative w-full h-auto mt-[6rem] bg-white mx-3"
            style={{ marginLeft: "19rem" }}
          >
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
